name: poketrade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.3
  - pip
  - numpy
  - pandas
  - pytorch
  - aiohttp
  - opencv
  - pip:
    - open_clip_torch
    - ultralytics
    - faiss-cpu
    - requests
    - tqdm
